// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Drei gängige Prüfsummen eines Datei-Inhalts.
 */
export type Checksums = { md5: string, sha1: string, sha256: string, };
