// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Three common checksums of a file's content.
 */
export type Checksums = { md5: string, sha1: string, sha256: string, };
