// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Namenskonflikt-Anfrage – Event "fs-collision".
 * Der Transfer-Thread wartet, bis das Frontend `resolve_collision` aufruft.
 */
export type CollisionReq = { transfer_id: string, req_id: string, 
/**
 * Zielpfad, der bereits existiert
 */
path: string, is_dir: boolean, };
