// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Name-conflict request – event "fs-collision".
 * The transfer thread waits until the frontend calls `resolve_collision`.
 */
export type CollisionReq = { transfer_id: string, req_id: string, 
/**
 * target path that already exists
 */
path: string, is_dir: boolean, };
