// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eine Zeile der Text-Gegenüberstellung (side-by-side).
 * `tag`: "equal" | "replace" | "delete" | "insert".
 */
export type DiffLine = { tag: string, left_no: number | null, left: string | null, right_no: number | null, right: string | null, };
