// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A comparison result for a file (relative to the two roots).
 */
export type DiffEntry = { 
/**
 * Relative path (separated by "/"), identical on both sides.
 */
rel: string, 
/**
 * Base name of the file.
 */
name: string, 
/**
 * Exists left / right.
 */
left: boolean, right: boolean, left_size: number, right_size: number, left_modified: number, right_modified: number, 
/**
 * "same" | "left_only" | "right_only" | "newer_left" | "newer_right" | "different"
 */
status: string, };
