// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ein Vergleichsergebnis für eine Datei (relativ zu den beiden Wurzeln).
 */
export type DiffEntry = { 
/**
 * Relativer Pfad (mit "/" getrennt), identisch auf beiden Seiten.
 */
rel: string, 
/**
 * Basisname der Datei.
 */
name: string, 
/**
 * Existiert links / rechts.
 */
left: boolean, right: boolean, left_size: number, right_size: number, left_modified: number, right_modified: number, 
/**
 * "same" | "left_only" | "right_only" | "newer_left" | "newer_right" | "different"
 */
status: string, };
