// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ein EXIF-Feld (Anzeigename + formatierter Wert).
 */
export type ExifTag = { name: string, value: string, };
