// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An EXIF field (display name + formatted value).
 */
export type ExifTag = { name: string, value: string, };
