// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLine } from "./DiffLine";
import type { HexRow } from "./HexRow";

/**
 * Gesamtergebnis eines Dateivergleichs.
 */
export type FileDiff = { 
/**
 * "text" | "binary"
 */
mode: string, 
/**
 * Ob beide Dateien byte-identisch sind.
 */
identical: boolean, 
/**
 * Ob das Ergebnis wegen der Größenobergrenzen gekürzt wurde.
 */
truncated: boolean, left_size: number, right_size: number, 
/**
 * Zeilen im Textmodus (sonst leer).
 */
lines: Array<DiffLine>, 
/**
 * Zeilen im Binärmodus (sonst leer).
 */
hex: Array<HexRow>, };
