// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { XattrItem } from "./XattrItem";

/**
 * Collected properties of an entry (result of `file_props`).
 */
export type FileProps = { path: string, name: string, is_dir: boolean, is_symlink: boolean, size: number, modified: number, 
/**
 * Full st_mode (incl. file-type bits); None on non-Unix.
 */
mode: number | null, uid: number | null, gid: number | null, 
/**
 * Resolved user name (or None if not resolvable/non-Unix).
 */
owner: string | null, group: string | null, xattrs: Array<XattrItem>, 
/**
 * ACL entries as text lines (empty if none/not supported).
 */
acl: Array<string>, 
/**
 * Whether the platform supports owner/xattr/ACL at all.
 */
unix: boolean, 
/**
 * Entry states the frontend colors by (see commands/fs/attrs.rs).
 * Same fields as `DirEntry`, so both resolve the same color rules.
 */
hidden: boolean, readonly: boolean, executable: boolean, };
