// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { XattrItem } from "./XattrItem";

/**
 * Gesammelte Eigenschaften eines Eintrags (Ergebnis von `file_props`).
 */
export type FileProps = { path: string, name: string, is_dir: boolean, is_symlink: boolean, size: number, modified: number, 
/**
 * Voller st_mode (inkl. Dateityp-Bits); None auf Nicht-Unix.
 */
mode: number | null, uid: number | null, gid: number | null, 
/**
 * Aufgelöster Benutzername (oder None, wenn nicht auflösbar/Nicht-Unix).
 */
owner: string | null, group: string | null, xattrs: Array<XattrItem>, 
/**
 * ACL-Einträge als Textzeilen (leer, wenn keine/nicht unterstützt).
 */
acl: Array<string>, 
/**
 * Ob die Plattform Besitzer/xattr/ACL überhaupt unterstützt.
 */
unix: boolean, };
