// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLine } from "./DiffLine";
import type { HexRow } from "./HexRow";

/**
 * Overall result of a file comparison.
 */
export type FileDiff = { 
/**
 * "text" | "binary"
 */
mode: string, 
/**
 * Whether both files are byte-identical.
 */
identical: boolean, 
/**
 * Whether the result was truncated due to the size limits.
 */
truncated: boolean, left_size: number, right_size: number, 
/**
 * Lines in text mode (otherwise empty).
 */
lines: Array<DiffLine>, 
/**
 * Lines in binary mode (otherwise empty).
 */
hex: Array<HexRow>, };
