// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitStatus = { is_repo: boolean, branch: string | null, 
/**
 * Name (top level in the folder) → status code
 * ("modified" | "new" | "deleted" | "renamed" | "conflict" | "ignored").
 */
entries: { [key in string]?: string }, };
