// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitStatus } from "./GitStatus";

/**
 * Payload of the `git-support-ready` event: folder path + associated status,
 * so the frontend can assign the result to the correct tab (even
 * if the folder has changed in the meantime).
 */
export type GitStatusEvent = { path: string, status: GitStatus, };
