// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitStatus } from "./GitStatus";

/**
 * Payload des Events `git-support-ready`: Ordnerpfad + zugehöriger Status,
 * damit das Frontend das Ergebnis dem richtigen Tab zuordnen kann (auch
 * wenn der Ordner inzwischen gewechselt wurde).
 */
export type GitStatusEvent = { path: string, status: GitStatus, };
