// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One 16-byte line of the hex comparison.
 */
export type HexRow = { offset: number, left_hex: string, left_ascii: string, right_hex: string, right_ascii: string, 
/**
 * Whether the two sides differ in this line.
 */
differs: boolean, };
