// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Eine 16-Byte-Zeile der Hex-Gegenüberstellung.
 */
export type HexRow = { offset: number, left_hex: string, left_ascii: string, right_hex: string, right_ascii: string, 
/**
 * Ob sich die beiden Seiten in dieser Zeile unterscheiden.
 */
differs: boolean, };
