// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Completion of a transfer – event "fs-done".
 */
export type OpDone = { id: string, op: string, ok: number, errors: Array<string>, cancelled: boolean, };
