// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ongoing progress of a transfer – event "fs-progress".
 * Two levels: current file (file_done/file_total) and
 * overall operation (bytes_done/bytes_total, files_done/files_total).
 */
export type OpProgress = { 
/**
 * Unique operation ID (assigned by the frontend).
 */
id: string, 
/**
 * "copy" | "move" | "extract" | "pack"
 */
op: string, 
/**
 * currently processed file (full path)
 */
file_name: string, file_done: number, file_total: number, files_done: number, files_total: number, bytes_done: number, bytes_total: number, 
/**
 * Whether the operation is currently paused (waiting to resume).
 */
paused: boolean, };
