// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Laufender Fortschritt eines Transfers – Event "fs-progress".
 * Zwei Ebenen: aktuelle Datei (file_done/file_total) und
 * Gesamtvorgang (bytes_done/bytes_total, files_done/files_total).
 */
export type OpProgress = { 
/**
 * Eindeutige Vorgangs-ID (vom Frontend vergeben).
 */
id: string, 
/**
 * "copy" | "move" | "extract" | "pack"
 */
op: string, 
/**
 * aktuell verarbeitete Datei (voller Pfad)
 */
file_name: string, file_done: number, file_total: number, files_done: number, files_total: number, bytes_done: number, bytes_total: number, 
/**
 * Ob der Vorgang gerade pausiert ist (wartet auf Fortsetzen).
 */
paused: boolean, };
