// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ergebnis einer synchronen Operation (z. B. Löschen).
 */
export type OpResult = { ok: number, errors: Array<string>, };
