// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExifTag } from "./ExifTag";

/**
 * Vorschau-Inhalt einer Datei: Text, Bild (data-URL) oder Hex (binär).
 */
export type Preview = { 
/**
 * "text" | "image" | "binary"
 */
kind: string, name: string, size: number, 
/**
 * Textfassung des gelesenen Ausschnitts (lossy UTF-8; auch bei Binärdateien).
 */
text: string | null, 
/**
 * Hex-Dump (nur bei kind = binary).
 */
hex: string | null, 
/**
 * data-URL (bei kind = image)
 */
data_url: string | null, 
/**
 * EXIF-Metadaten (nur bei Bildern; sonst leer).
 */
exif: Array<ExifTag>, 
/**
 * true, wenn nur ein Anfangsausschnitt gelesen wurde
 */
truncated: boolean, };
