// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExifTag } from "./ExifTag";

/**
 * Preview content of a file: text, image (data URL), or hex (binary).
 */
export type Preview = { 
/**
 * "text" | "image" | "binary"
 */
kind: string, name: string, size: number, 
/**
 * Text version of the read excerpt (lossy UTF-8; for binary files too).
 */
text: string | null, 
/**
 * Hex dump (only for kind = binary).
 */
hex: string | null, 
/**
 * data URL (for kind = image)
 */
data_url: string | null, 
/**
 * EXIF metadata (only for images; otherwise empty).
 */
exif: Array<ExifTag>, 
/**
 * true if only an initial excerpt was read
 */
truncated: boolean, };
