// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A search hit (file or folder).
 */
export type SearchHit = { path: string, name: string, is_dir: boolean, size: number, modified: number, 
/**
 * Additional info: match line (content), size, or group hint.
 */
detail: string, 
/**
 * Duplicate group (>0 in "duplicates" mode; otherwise 0).
 */
group: number, };
