// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ein Suchtreffer (Datei oder Ordner).
 */
export type SearchHit = { path: string, name: string, is_dir: boolean, size: number, modified: number, 
/**
 * Zusatzinfo: Trefferzeile (Inhalt), Größe oder Gruppenhinweis.
 */
detail: string, 
/**
 * Duplikatgruppe (>0 im Modus „duplicates"; sonst 0).
 */
group: number, };
