// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Finder tag: name plus color index (0 = none, 1–7 = Finder colors).
 */
export type Tag = { name: string, color: number, };
