// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ein Finder-Tag: Name plus Farbindex (0 = keine, 1–7 = Finder-Farben).
 */
export type Tag = { name: string, color: number, };
