// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An extended attribute: name, size of the raw value, and – if the
 * value is printable UTF-8 text – a truncated text preview.
 */
export type XattrItem = { name: string, size: number, 
/**
 * UTF-8 preview (max. 256 characters) or None for binary data.
 */
value: string | null, };
