// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ein Extended Attribute: Name, Größe des Rohwerts und – sofern der
 * Wert druckbarer UTF-8-Text ist – eine gekürzte Textvorschau.
 */
export type XattrItem = { name: string, size: number, 
/**
 * UTF-8-Vorschau (max. 256 Zeichen) oder None bei Binärdaten.
 */
value: string | null, };
